services:
  web:
    build: .
    container_name: web_app_practica7
    ports:
      - "8080:5000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_practica7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: practica_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:services:
  web:
    build: .
    container_name: web_app_practica7
    ports:
      - "8080:5000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_practica7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: practica_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: